create table if not exists public.user_app_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  subscription jsonb not null,
  notification_hour integer not null default 8 check (notification_hour between 0 and 23),
  timezone text not null default 'Asia/Tokyo',
  enabled boolean not null default true,
  last_notification_key text,
  created_at timestamptz not null default now(),
  unique(user_id, endpoint)
);

alter table public.user_app_state enable row level security;
alter table public.push_subscriptions enable row level security;

create policy "own app state" on public.user_app_state
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own push subscriptions" on public.push_subscriptions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

